<%
  branch = `git rev-parse --abbrev-ref HEAD`.strip rescue nil
  branch = branch.gsub('/', '_')
  local_env = YAML.load_file("#{Rails.root}/local_env.yml").dig(Rails.env) || {}

  if(local_env.dig('devdb') != nil)
    branch = local_env.dig('devdb')
  end
%>

default: &default
  encoding: utf8mb4
  collation: utf8mb4_bin
  adapter:   mysql2
  username:  <%= local_env.dig('database', 'username') %>
  password:  <%= local_env.dig('database', 'password') %>
  <% if(local_env.dig('database', 'host') != nil) %>
  host:  <%= local_env.dig('database', 'host') %>
  <% end %>
  <% if(local_env.dig('database', 'port') != nil) %>
  port:  <%= local_env.dig('database', 'port') %>
  <% end %>

development:
  <<: *default
  database:  govcraft_development_<%= branch %>

test:
  <<: *default
  database:  govcraft_test_<%= branch %>


<%
def determine_adapter
  if Gem.loaded_specs.key?("mysql2")
    "mysql2"
  else
    "mysql"
  end
rescue
  "mysql"
end
%>

production:
  adapter:    <%= determine_adapter %>
  database:   '<%= ENV.fetch("DATABASE_NAME") { "DEFAULT_DATABASE_NAME" } %>'
  username:   '<%= ENV.fetch("DATABASE_USERNAME") { "DEFAULT_DATABASE_USERNAME" } %>'
  password:   '<%= ENV.fetch("DATABASE_PASSWORD") { "DEFAULT_DATABASE_PASSWORD" } %>'
  host:       '<%= ENV.fetch("DATABASE_HOST") { "DEFAULT_DATABASE_HOST" } %>'
  pool:       <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding:   utf8mb4
  collation:  utf8mb4_unicode_ci
  reconnect:  true
