<%
  branch = `git rev-parse --abbrev-ref HEAD`.strip rescue nil
  branch = branch.gsub('/', '_')
  local_env = YAML.load_file("#{Rails.root}/local_env.yml").dig(Rails.env) || {}
%>

default: &default
  encoding: utf8mb4
  collation: utf8mb4_bin
  adapter:   mysql2
  username:  <%= local_env.dig('database', 'username') %>
  password:  <%= local_env.dig('database', 'password') %>
  <% if(local_env.dig('database', 'host') != nil) %>
  host:  <%= local_env.dig('database', 'host') %>
  <% end %>
  <% if(local_env.dig('database', 'port') != nil) %>
  port:  <%= local_env.dig('database', 'port') %>
  <% end %>

development:
  <<: *default
  database:  govcraft_development_<%= branch %>

test:
  <<: *default
  database:  govcraft_test_<%= branch %>
